In [4]:
#Q.1 - Create a numpy array with 10 elements of the shape(10,1) using np.random and 
#find out the mean of the elements using basic numpy functions.
import numpy as np
arr=np.random.rand(10,1)
print(arr)
print(arr.mean())

[[0.19490904]
 [0.09875547]
 [0.72531972]
 [0.99137311]
 [0.81847121]
 [0.29210854]
 [0.07120841]
 [0.24655002]
 [0.63274403]
 [0.74320436]]
0.4814643909279579


In [10]:
#Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random 
#find the variance and standard deviation of the elements.
arr=np.random.rand(20,1)
print(arr)
print(arr.var())
print(arr.std())

[[6.14869012e-01]
 [6.29509317e-01]
 [8.79666101e-01]
 [2.05442630e-01]
 [9.27595880e-01]
 [8.54141575e-01]
 [7.44852046e-01]
 [2.31078308e-02]
 [7.54594614e-01]
 [2.38320070e-01]
 [3.19774482e-01]
 [1.59186407e-01]
 [3.30436560e-04]
 [4.27578892e-01]
 [7.23820007e-01]
 [8.38005867e-01]
 [5.54594251e-02]
 [6.61738614e-01]
 [7.74203746e-01]
 [5.42998475e-01]]
0.0925736292353211
0.30425914815387406


In [18]:
#Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. 
#Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25).
#Using basic numpy math functions only find the sum of all the elements of the new matrix.
arrA=np.random.rand(10,20)
arrB=np.random.rand(20,25)
C=np.matmul(arrA,arrB)
print(np.shape(C))
print(np.sum(C))

(10, 25)
1270.9611141261541


In [24]:
#Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an 
#array of shape(10,1) such that each element is the following function applied on each element of A. 
#f(x)=1 / (1 + exp(-x))
arr=np.random.rand(10,1)
def fun(a):
    return 1 / (1 + np.exp(-a))
arr1=np.apply_along_axis(fun,1,arr)
print(arr1)

[[0.50887334]
 [0.82225132]
 [0.0150731 ]
 [0.16455391]
 [0.78235803]
 [0.66802683]
 [0.00359333]
 [0.49021592]
 [0.52030913]
 [0.89592698]]
[[0.62454232]
 [0.69471402]
 [0.5037682 ]
 [0.5410459 ]
 [0.6861881 ]
 [0.66106119]
 [0.50089833]
 [0.6201573 ]
 [0.62722005]
 [0.71011178]]
